### ISSUE TITLE
Event example

### ISSUE THREAD

**Issue by salvdev** [Quintor/angular-truffle-box#28] opened 2018-03-09 08:33 UTC
Can we get an example of receiving an Event when updating the state of a contract?

For example the sendCoin() function in the MetaCoin.sol file emits a Transfer event when successfully evoked. How does one console.log this Event when sent back to the client?

**Comment by pimotte** [comment] 2018-03-09 10:04
Yep, this is something that would be a useful addition (see #10). 

If I start working on this, I'll let you know. If someone else wants to pick it up, let me know, and I'll be happy to review and merge it.

**Comment by pimotte** [comment] 2018-04-02 07:45
Closing this as a duplicate of #10

**Closed by pimotte** 2018-04-02 07:45 UTC
